checks:
  python:
    code_rating: true
    duplicate_code: true
build:
  environment:
    python:
      version: 3.7.1
  nodes:
    analysis:
      project_setup:
        override:
          - "true"
      tests:
        override:
          - py-scrutinizer-run
          - command: pylint-run
            use_website_config: false
    tests: true
filter:
  excluded_paths:
    - "tests/*"
